### ISSUE TITLE
Como funciona o input da config?

### ISSUE THREAD

**Issue by vieiraroger** [fraterblack/projeto-teoria-grafos#11]
Na configuração ele vai informar a rota inteira para criacao das pastas? Ou a rota apartir do C:?

**Comment by fraterblack** [comment]
A princípio deixamos os input text para o usuário digitar o caminho que quiser. Depois podemos usar um componente seletor de diretório para facilitar

**Comment by vieiraroger** [comment]
Se não me engano tem que ter 3 pastas, porem nesse caso tem 1 diretorio e 2 pastas:

```
createSingleFolder(config.getFolder());
createSingleFolder(config.getFolder() + "//" + config.getError());
createSingleFolder(config.getFolder() + "//" + config.getSucess());
```

Podemos falar com o professor mas pelo o que eu havia intendido, ele poderia escolher o local de cada arquivo.
Por exemplo, por o sucess no desktop e o error na pasta Users do sistema.
Posso estar enganado.

**Comment by vieiraroger** [comment]
 Pasta: Conterá o diretório raiz da aplicação;
 Sucesso: Diretório contendo os arquivo processados com sucesso;
 Erro: Diretório contendo os arquivos processados com erro
Achei aqui, ta certo
