### ISSUE TITLE
Dijkstra não está criando o caminho correto até o destino

### ISSUE THREAD

**Issue by fraterblack** [fraterblack/projeto-teoria-grafos#14]
O algoritmo está calculando corretamente a distância da origem até o destino.
Porém não está ignorando as matrizes com valor zero, o que se configura como não existindo rota.

**Comment by vieiraroger** [comment]
Tentei pesquisar sem caminho e o PC crashou e quase deu pal no servidor aqui da loja.
Toma cuidado quando for testar.

**Comment by vieiraroger** [comment]
Done
