### ISSUE TITLE
Recuperar configurações do arquivo de dados e instanciar o objeto Configuration no controller principal

### ISSUE THREAD

**Issue by fraterblack** [fraterblack/projeto-teoria-grafos#4]

**Comment by vieiraroger** [comment]
Criado função para pegara configuração de volta.

Commits:
37fb7cabb88e136b62beee067775c5cc939d912e
2adecdf8c1acf162b5f51247d8fae54007a0e839

Obs: Quando criado um arquivo de configurização é criado um HASH para demonstrar a integridade dos arquivos, impedindo então manipulação dele diretamente.

Exemplo de arquivo de configuração:
```
folder
sucess
error
false
fdaab882204023c62906224714415ef2
```
TO DO: Criar controller principal e utilizar a função.

Acho que pode fechar o issue. @fraterblack

**Comment by vieiraroger** [comment]
Done
770a1be09867521f0faf60b39655b2a91863ffa5
