### ISSUE TITLE
Implementar a lógica para salvar/editar as configurações apartir da tela

### ISSUE THREAD

**Issue by fraterblack** [fraterblack/projeto-teoria-grafos#5]

**Comment by vieiraroger** [comment]
Devemos criar um arquivo txt na base do nosso codigo para salvar a configuração?
Ou criamos ela em alguma pasta expecifica tipo "sucesso"?

**Comment by fraterblack** [comment]
Penso que pode ser criada na pasta usuarios

**Comment by vieiraroger** [comment]
Na verdade na configuração se não me engano ele diz o diretoria, chamado de Folder.
Acredito que deva ser o local onde deve ter as pastas.

**Comment by vieiraroger** [comment]
Esquece viagei, estou desenvolvendo

**Comment by fraterblack** [comment]
Fiz algumas mudanças na implementação dos diretórios. Se o usuário vai setar os diretórios, não precisa a gente criar pastas do tipo "pasta", "sucesso" e "erro"
